### ISSUE TITLE
Recompressed TOTK RESTBL crashes game at startup

### ISSUE THREAD

**Issue by ShrineFox** [EPD-Libraries/cs-restbl#1]
Hi! While this isn't technically caused by your tool, I was wondering how you would handle/account for this situation.  
When I [recompress](https://github.com/TotkMods/Totk.ZStdTool) ResourceSizeTable.Product.100.rsizetable.zs with ZSTD (whether I changed a CRC entry size or not), the game doesn't make it to the title screen without crashing (tested on RyujiNX).  
  
Is there something else that has to be changed to account for the size difference of the new RSTB file? Or is there another way around this?

**Comment by ArchLeaders** [comment]
Are you just loading the recompressed RESTBL? Or are you asking if there's another size variable table (like the RESTBL) to account for another file changing?

If it is the latter, what file did you change that you are updating?

**Comment by ShrineFox** [comment]
It's the former. Originally I was editing the entry size for Pack/Actor/Player.pack.zs, since when recompressed it becomes larger and crashes the game. But I haven't successfully launched the game at all with an unedited but recompressed RESTBL on its own, even with no other mods or changes.

**Comment by ArchLeaders** [comment]
Not sure what it could be then. I haven't actually done any modding yet, just parsing formats and such. My only thought is that it's not intended to be compressed with the common dictionary, which ZstdTool will do by default. I'm not sure how to discern what files use the dictionaries either though.

**Comment by ShrineFox** [comment]
Ah okay, that makes sense. Thanks for the clarification! If that ends up being the case, I'm surprised it was able to be decompressed successfully with the zs.zsdic dictionary. I was able to serialize it with this library just fine afterwards. I guess it's worth trying the other ones just in case though

**Comment by ShrineFox** [comment]
Thanks again for pointing me in the right direction-- I finally realized it works perfectly fine to recompress the RSTB with regular ZSTD compression through Toolbox (no TOTK dictionary). Wouldn't have thought of it without your input. Cheers! 👍

**Comment by ArchLeaders** [comment]
Awesome, I guess now we just need to figure out what makes something dictionary-compressible

**Comment by Melechtna** [comment]
> Awesome, I guess now we just need to figure out what makes something dictionary-compressible

Well, the rstbl can be read without any dictionaries by KDEs compressed file browser (Arc) without any special non-sense, just double click and it can open it, so a simple check with zstd if it can read out the contents without a dictionary would likely help.

**Comment by ArchLeaders** [comment]
That sounds highly inefficient and kind of pointless for the purpose of compressing arbitrary data. I'll keep it in mind though if I come across any other similar issues.

**Comment by Melechtna** [comment]
> That sounds highly inefficient and kind of pointless for the purpose of compressing arbitrary data. I'll keep it in mind though if I come across any other similar issues.

Seeing if the file returns a result by making a simple list request is inefficient? I'm not saying extract the thing, just read the contents, if it returns an error, it likely needs a dictionary or isn't compatible yet, if it returns a result, then it can be worked upon and should be treated as a "no dic needed" type or something along those lines.

**Comment by ArchLeaders** [comment]
I suppose that wouldn't be too bad, but using try/catch for logic is usually a bad idea. The main issue is compression, decompressing is easy enough.

**Comment by Melechtna** [comment]
> I suppose that wouldn't be too bad, but using try/catch for logic is usually a bad idea. The main issue is compression, decompressing is easy enough.

You could probably skip the try catch by simply passing the result to a variable and running a simple notnull, but I'm unsure which language you're specifically using in this case.

**Comment by ArchLeaders** [comment]
In this case I don't have that much control over the processing, it's in C# calling a native function, so it'll either throw an interop exception or just crash the thing entirely. But as I said, this really isn't the issue.
