### ISSUE TITLE
Was told to come here for what is likely a UI issue, but here I am

### ISSUE THREAD

**Issue by Melechtna** [EPD-Libraries/cs-restbl#2]
In Linux, the project using this lib can't be compiled due to this specific error

`115/198] Building CXX object lib/restbl/lib/abseil/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/float_conversion.cc.o
FAILED: lib/restbl/lib/abseil/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/float_conversion.cc.o 
/usr/bin/c++  -I/home/melechtna/src/NxEditor/lib/cs-restbl/native/lib/restbl/lib/abseil -O3 -DNDEBUG -std=c++17 -fPIC -Wall -Wextra -Wcast-qual -Wconversion-null -Wformat-security -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -DNOMINMAX -MD -MT lib/restbl/lib/abseil/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/float_conversion.cc.o -MF lib/restbl/lib/abseil/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/float_conversion.cc.o.d -o lib/restbl/lib/abseil/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/float_conversion.cc.o -c /home/melechtna/src/NxEditor/lib/cs-restbl/native/lib/restbl/lib/abseil/absl/strings/internal/str_format/float_conversion.cc
In file included from /home/melechtna/src/NxEditor/lib/cs-restbl/native/lib/restbl/lib/abseil/absl/strings/internal/str_format/float_conversion.h:18,
                 from /home/melechtna/src/NxEditor/lib/cs-restbl/native/lib/restbl/lib/abseil/absl/strings/internal/str_format/float_conversion.cc:15:
`

In Windows however, the issue is entirely different, there are no errors in the console, but when loading the table, I get precisely nothing as show below
![Screenshot_20230613_215624](https://github.com/EPD-Libraries/cs-restbl/assets/81296467/cc9eb1c2-e8a2-4e7f-95cb-298b2ef3900d)
It doesn't matter what I have in the search bar, it's always blank

**Comment by Melechtna** [comment]
Dev needs to stop hiding essential files in a discord.

**Comment by ArchLeaders** [comment]
The first issue is an error with the c++ library, not the C# wrapper. The latter isn't an issue at all, nor by any means related to this library wrapper.
